version: '3.8'

services:
  web:
    image: crm_nato:latest
    build:
      context: .
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
